version: '3.3'

services:
  redis:
    image: 'redis:alpine'
    container_name: pub_sub
    ports:
      - '6379:6379'

  backend:
    restart: "on-failure"
    build: ./
    volumes:
      - ./:/var/www/app
    ports:
      - "3000:3000"
    env_file: ./.env
    links:
      - redis
    environment:
      - REDIS_HOST=pub_sub
      - REDIS_PORT=6379
    command:
      npm run deploy
